image: gitlab.futo.org:5050/baremetal/ret/wrangler:latest

stages:
  - deploy


deploy_to_cloudflare_test:
  stage: deploy
  script:
    - |
      git submodule update --init --recursive --depth 1
      make config_all -j`nproc`
      make build_all
      make deploy
      echo "google-site-verification: google38b8ae97460b2987.html" > deploy/google38b8ae97460b2987.html
      npx wrangler pages deploy ./deploy --branch main --project-name=ret-test
  artifacts:
    paths:
      - deploy/
    expire_in: 1 day

deploy_to_cloudflare_prod:
  stage: deploy
  needs: [deploy_to_cloudflare_test]
  script:
    - |
      npx wrangler pages deploy ./deploy --branch main --project-name=ret-prod
  only:
    - tags
