image: gitlab.futo.org:5050/baremetal/ret/wrangler:latest

stages:
  - deploy

deploy_to_cloudflare:
  stage: deploy
  script:
    - |
      git submodule update --init --recursive
      make config_all -j`nproc`
      make build_all
      make deploy
      echo "google-site-verification: google38b8ae97460b2987.html" > deploy/google38b8ae97460b2987.html
