name: Compile and deploy ret

on:
  push:
    branches: [master]
#on:
#  create

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deps
        run: |
          sudo apt update
          sudo apt install -y emscripten cmake ninja-build

      - name: Compile 3 arches
        run: |
          make config_all -j`nproc`
          make build_all

#      - name: Setup root
#        run: |
#          cp build/ret.js www/
#          cp build/ret.wasm www/
#
#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v4
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./www
#
