name: Compile and deploy ret

on:
  push:
    branches: [master]
#on:
#  create

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Deps
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build
      - name: emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Compile 3 arches
        run: |
          make CMAKE=~/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake config_all -j`nproc`
          make CMAKE=~/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake build_all

      - name: Setup root
        run: |
          make deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy

